### ISSUE TITLE
我之前下载过一次，那个没有问题，这个报错了，下面是报错信息。

### ISSUE THREAD

**Issue by wanglu123run** [NeglectedByBoss/RetrofitClient#1]
08-22 19:06:40.743 6767-6767/com.tamic.retrofitclient E/Tamic: java.io.IOException: unexpected end of stream on okhttp3.Address@ecf82dd4
08-22 19:06:40.743 6767-6767/com.tamic.retrofitclient E/Lyk: java.io.IOException: unexpected end of stream on okhttp3.Address@ecf82dd4

08-22 19:06:58.273 6767-6767/com.tamic.retrofitclient E/Tamic: java.net.SocketTimeoutException
08-22 19:06:58.273 6767-6767/com.tamic.retrofitclient E/Lyk: java.net.SocketTimeoutException

08-22 19:07:06.173 6767-6767/com.tamic.retrofitclient E/Tamic: com.google.gson.internal.LinkedTreeMap cannot be cast to com.tamic.retrofitclient.IpResult
08-22 19:07:06.173 6767-6767/com.tamic.retrofitclient E/Lyk: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.tamic.retrofitclient.IpResult

08-22 19:09:22.093 11669-11669/com.tamic.retrofitclient E/Tamic: java.lang.ClassCastException: okhttp3.ResponseBody$1 cannot be cast to com.tamic.retrofitclient.net.BaseResponse
08-22 19:09:22.093 11669-11669/com.tamic.retrofitclient E/Lyk: java.lang.ClassCastException: okhttp3.ResponseBody$1 cannot be cast to com.tamic.retrofitclient.net.BaseResponse

**Comment by Tamicer** [comment]
服务端饭回的body默认是 linkedTreeMap 无法转化为具体bean ，我看看不行得加个转换器 默认转化String 再之后上层手动序列化为实体
