### ISSUE TITLE
RuntimeExcepiton

### ISSUE THREAD

**Issue by PoisonLeon** [NeglectedByBoss/RetrofitClient#13]
运行报错RuntimeExcepiton

动态url传入拼接报错。
日志显示 ：
动态URL最终拼接后
<-- 200 OK http://ip.taobao.com/service%2FgetIpInfo.php?ip=21.22.11.33 (13ms)
普通的
 http://ip.taobao.com/service/getIpInfo.php?ip=21.22.11.33 (11ms)
。

**Comment by Tamicer** [comment]
这个你直接用@url 注解符号
