### ISSUE TITLE
你好,关于图文上传的方法

### ISSUE THREAD

**Issue by sweet2o09** [NeglectedByBoss/RetrofitClient#15]
你好,
我APP内用的是这个方法上传图片+参数
    @POST()
    Flowable<ResponseBody> upload(@Url String url, @Body RequestBody Body);

调用方式如下:
public Flowable<ResponseBody> upload(String url, Map<String, String> params, Map<String, String> files) {
            final MultipartBody.Builder builder = new MultipartBody.Builder().setType(MultipartBody.FORM);
            Flowable.fromIterable(params.entrySet()).subscribe(
                    new Consumer<Map.Entry<String, String>>() {
                        @Override
                        public void accept(Map.Entry<String, String> entry) throws Exception {
                            builder.addFormDataPart(entry.getKey(), entry.getValue());
                        }
                    });
            if (files != null && files.size() > 0) {
                //多张图片
                Flowable.fromIterable(files.entrySet()).subscribe(
                        new Consumer<Map.Entry<String, String>>() {
                            @Override
                            public void accept(Map.Entry<String, String> entry) throws Exception {
                                File file = new File(entry.getValue());//filePath 图片地址
                                RequestBody imageBody = RequestBody.create(MediaType.parse("image/*"), file);
                                builder.addFormDataPart(entry.getKey(), file.getName(),imageBody);
                            }
                        });
            }
            LogUtils.d(API_TAG, "upload url = " + url +
                    " :: params = " + params.toString() +
                    " :: files = " + files.toString());
            return bindLifeCycle(getIBaseService().upload(url, builder.build()));
        }

结果发现服务器那边都收不到我发送过去的图片,不知道什么原因,请问你们一般是如何上传图片+参数的呢?

**Comment by Tamicer** [comment]
这个我写过一篇博客
