### ISSUE TITLE
每一个请求都报错

### ISSUE THREAD

**Issue by dz-hexiang** [NeglectedByBoss/RetrofitClient#16]
点第一请求个出现：com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 19 path $.data

点第二个请求出现：java.lang.RuntimeException

**Comment by Tamicer** [comment]
@dz-hexiang 数据解析出错了 请按标准格式返回数据
