### ISSUE TITLE
demo有问题

### ISSUE THREAD

**Issue by xj999** [NeglectedByBoss/RetrofitClient#3]
java.lang.ClassCastException: okhttp3.ResponseBody$1 cannot be cast to com.tamic.retrofitclient.net.BaseResponse 
一直提示这个 无法转换

**Comment by Tamicer** [comment]
我看看 第一版是可以的 后面我加入了反射 估计可能有问题

**Comment by xj999** [comment]
还有想问下   gson解析部分在哪  是完全交给retrofit处理了吗

**Comment by Tamicer** [comment]
对的 这个看你申明的接口是具体对象还是ResponseBody 如果是具体bean那么就是retrofit 来处理
如果是ResponseBody 就是RetrofitClient来处理

**Comment by xj999** [comment]
请问这个异常什么时候能修复

**Comment by Tamicer** [comment]
今天我看看

**Comment by Tamicer** [comment]
@GET("{url}")
    Observable<BaseResponse<Object>> executeGet(
            @Path("url") String url,
            @QueryMap Map<String, String> maps
           );

把apiservice中改成下面就行了 Object改成IpResult就可以了
 @GET("{url}")
    Observable<BaseResponse<IpResult>> executeGet(
            @Path("url") String url,
            @QueryMap Map<String, String> maps
           );

**Comment by Tamicer** [comment]
此项目已不更新了， 建议使用novate: https://github.com/Tamicer/Novate
