### ISSUE TITLE
demo用不了，网络错误

### ISSUE THREAD

**Issue by maxiaoyi** [NeglectedByBoss/RetrofitClient#4]
请求404了，作者可以重新修改看看不?

**Comment by Tamicer** [comment]
那是你服务端的数据没进行　ｃｏｄｅ　ｍｓｇ　和ｄａｔａ　个格式返回

**Comment by Tamicer** [comment]
@maxiaoyi  404请检查你的url 和请求方式。此项目已更新了了， 建议使用novate: https://github.com/Tamicer/Novate
