### ISSUE TITLE
大文件无法下载

### ISSUE THREAD

**Issue by gaoyuan117** [NeglectedByBoss/RetrofitClient#9]
大神 我现在下载大文件，点击下载一直没有反应，小文件是没有问题的，怎么解决

**Comment by Tamicer** [comment]
@gaoyuan117 报啥错 你是用的哪个版本？

**Comment by gaoyuan117** [comment]
我就是复制的你的部分代码，没有错误，

**Comment by gaoyuan117** [comment]
小文件下载是没有问题的，但是下载大文件的时候，提示 下载开始 后就没有反应了

**Comment by Tamicer** [comment]
@gaoyuan117 参考novate 源码 吧 rettofit有个坑 你需要提前知道大文件还是小文件， 大文件 需要用@stream 修饰

**Comment by gaoyuan117** [comment]
加上了  也不行..

**Comment by Tamicer** [comment]
@gaoyuan117 读写操作要在子线程中

**Comment by Tamicer** [comment]
@gaoyuan117  建议使用 https://github.com/Tamicer/Novate
